---
sfx_sources:
- label: prod_sfx
  realm: eu0
  token: NM76t62cT-dSWpqgWOdHcA
  cycle: 60
  targets:
  - prod_splunk
- label: stage_sfx
  realm: eu0
  token: NM76t62cT-dSWpqgWOdHcA
  cycle: 25
  targets:
  - stage_splunk
  - prod_textfile
targets:
- label: prod_splunk
  type: splunk
  hec_url: http://localhost:8088/services/collector
  hec_token: aa18b9dd-ea02-4c63-941b-b5f8e1061d59
  source: splunk_sas
  sourcetype: alex_st
  index: alex_test
- label: stage_splunk
  type: splunk
  hec_url: http://localhost:8088/services/collector
  hec_token: aa18b9dd-ea02-4c63-941b-b5f8e1061d59  
- label: prod_textfile
  type: file
  file_name: /alex.txt