apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  labels:
    app: splunk-o11y-sas
  name: splunk-o11y-sas-otel-collector
spec:
  mode: sidecar
  env:
    - name: SPLUNK_REALM
      value: eu0                         # us1 is for dev, us2 is for stage & prod
    - name: SPLUNK_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          key: SPLUNK_ACCESS_TOKEN       # you need to provide a secret with your
          name: otel-test-container       # SignalFx ingest token
  config: |-
    exporters:
      signalfx:
        access_token: "${SPLUNK_ACCESS_TOKEN}"
        ingest_url: "https://ingest.${SPLUNK_REALM}.signalfx.com/v2/datapoint"
        realm: "${SPLUNK_REALM}"
    processors:
      batch: {}
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: "splunk-o11y-sas"
            scrape_interval: "60s"
            metrics_path: "/metrics"
            static_configs:
            - targets:
              - "localhost:2112"
    service:
      pipelines:
        metrics:
          exporters:
          - signalfx
          processors:
          - batch
          receivers:
          - prometheus