---
sfx_sources:
- label: tinman_sfx
  realm: eu0
  token: token
  cycle: 60
  targets:
  - prod_splunk
- label: stage_sfx
  realm: eu0
  token: token
  cycle: 25
  targets:
  - stage_splunk
  - prod_textfile
targets:
- label: prod_splunk
  type: splunk
  hec_url: http://localhost:8088/services/collector
  hec_token: token
  source: splunk_sas
  sourcetype: alex_st
  index: alex_test
- label: stage_splunk
  type: splunk
  hec_url: https://10.202.4.238:8088/services/collector
  hec_token: token  
- label: prod_textfile
  type: file
  file_name: /alex.txt
